[package]
name = "base64_tool"
version = "0.1.0"
edition = "2021"
description = "base64 工具"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
flate2 = { version = "1.0.17" }